---
# tasks file for nginx

- name: Adding nginx_signing key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: Adding Nginx Apt Repository
  shell: echo "deb-src http://nginx.org/packages/mainline/ubuntu/ `lsb_release -cs` nginx"  >> /etc/apt/sources.list

- name: Adding Nginx Apt Repository
  shell: echo "deb http://nginx.org/packages/mainline/ubuntu/ `lsb_release -cs` nginx" >> /etc/apt/sources.list

- name: apt get update
  apt:
    update_cache: yes

- name: Install nginx
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - nginx
    - git

- name: Start nginx
  become: yes
  service:
    name: nginx
    state: started

- name: Update nginx confs for WordPress + PHP
  template: "src=../templates/localhost.conf dest=/etc/nginx/conf.d/localhost.conf owner=www-data group=www-data mode=0644"
  become: yes

- name: Update nginx confs for WordPress + PHP
  file: path=/etc/nginx/conf.d/default.conf state=absent
  become: yes
