---
# tasks file for php

- name: Install php extensions
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - php7.3
    - php7.3-fpm
    - php7.3-mysql

- name: Setup php-fpm
  replace: dest=/etc/php/7.3/fpm/pool.d/www.conf regexp="(listen = /run/php/php7.3-fpm.sock)" replace='listen = 127.0.0.1:9000'
  notify:
    - restart nginx
    - restart php7.3-fpm
  become: yes

